### PR TITLE
feat: add string length validators and tests

### PR DESCRIPTION
**Pull request by aman-waterdip**
add: added validator for string

### Fixes/Implements #
- #218

## Description

Summary Goes here.

## Type of change

Delete irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [x] Locally Tested
- [ ] Needs Testing From Production

### CODE REVIEW

**Review by subhankarb — APPROVED** [review]
LGTM

**Comment by aman-waterdip** [comment]
I've squashed the commits into one as requested.

**Comment by Ryuk-me** [comment]
Missing test cases for configuration parser @aman-waterdip 
please add it in `tests/core/configuration/test_configuration_v1.py`

**Comment by aman-waterdip** [comment]
i have added test cases for configuration parser

**Pull request closed without merging**
